### ISSUE TITLE
Add the possibility to abort a task

### ISSUE THREAD

**Issue by AzHicham** [ayrat555/fang#107]
Hello, 

First of all, I would like to say that I love your library. 
As you probably know, the rust ecosystem does not have (yet) a complete production-grade equivalent to celery/dramatiq for python. 

For now, I would like to know if it is possible to add a feature for aborting a task (by task_id ?), either a task still not processed by a worker or a task not finished yet.

EDIT: Also, is there a way to create a client (for pushing task) without the impl of the task ? 
in my case the worker is pretty heavy (lots of dependencies …) and I don’t want to build my client with all these dependencies. 

Thank you a lot !!!!

**Comment by ayrat555** [comment]
@AzHicham hey

> For now, I would like to know if it is possible to add a feature for aborting a task (by task_id ?), either a task still not processed by a worker or a task not finished yet.

it's possible to abort a task using:
- blocking api - https://docs.rs/fang/0.10.0/fang/blocking/queue/struct.Queue.html#method.remove_task
- async api - https://docs.rs/fang/0.10.0/fang/asynk/async_queue/struct.AsyncQueue.html#method.remove_task

also, it's possible to remove task based on its metadata ([remove_task_by_metadata](https://docs.rs/fang/0.10.0/fang/asynk/async_queue/trait.AsyncQueueable.html#tymethod.remove_task_by_metadata))

> EDIT: Also, is there a way to create a client (for pushing task) without the impl of the task ?
in my case the worker is pretty heavy (lots of dependencies …) and I don’t want to build my client with all these dependencies.

It's possible. the only thing `fang` needs is `Runnable` or `AsyncRunnable` trait implementations

**Comment by AzHicham** [comment]
Thanks a lot I didn't see that part of the API !!! 
So if in the client I create a MyTask struct with a dummy impl of Runnable and in the worker the same MyTask struct with the real impl it should work ?

**Comment by ayrat555** [comment]
yes, it should work

**Comment by AzHicham** [comment]
Nice I'll give it a try !!!
