### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Wulf** [ayrat555/fang#119]
Hey @ayrat555 and @pxp9,

I hope you're both doing well -- I just wanted to say thanks for this wonderful crate. It's because of efforts like this that the rust ecosystem can continue to grow and see more adoption.

**Comment by pxp9** [comment]
Thank you so much @Wulf

**Comment by pxp9** [comment]
Hey @Wulf We are back !!!

This summer we are planning to implement some more features.

More backends

SQLite Backend
InMemory Backend

Maybe also 

SurrealDb backend.

**Comment by Wulf** [comment]
Great to hear. I’ll be sure to lookout for the updates :)

We’re using fang in create-react-app but only if end users choose postgres as their backend. Would love to see SQLite support! 🙌

**Comment by IgnisDa** [comment]
@pxp9 Can you tell more about the in-memory backend. I was sent here from a reddit [suggestion](https://www.reddit.com/r/rust/comments/16cinmw/comment/jzk8on1/?utm_source=share&utm_medium=web2x&context=3).

**Comment by pxp9** [comment]
> @pxp9 Can you tell more about the in-memory backend. I was sent here from a reddit [suggestion](https://www.reddit.com/r/rust/comments/16cinmw/comment/jzk8on1/?utm_source=share&utm_medium=web2x&context=3).

Sure, In memory backend will be supported when SQLite is supported.

SQLite has a mode that it is in memory.

As you can see #141 pr , SQLite is implemented for `asynk` module. 

There is not support yet for `blocking` module.

We are working to have a multiple queues support and ensure that performance and reliability are good.
