### ISSUE TITLE
Implement async worker

### ISSUE THREAD

**Issue by ayrat555** [ayrat555/fang#38]
1. let's call it AsyncWorker. I think it will store AsyncQueue and some configuration parameters 

this struct can be created with TypedBuilder

2. create looping that will be fetching tasks and executing them

3. if there are no tasks, it should sleep

**Comment by pxp9** [comment]
Async Worker implemented with tests :D

**Comment by ayrat555** [comment]
implemented in https://github.com/ayrat555/fang/pull/46
