### ISSUE TITLE
Add support for SQLite

### ISSUE THREAD

**Issue by prabirshrestha** [ayrat555/fang#84]
I see that fang uses traits to implement `AsyncQueueable`. It would be great is SQLite is supported as it allows to build applications that just works without additional installation and configuration and they can always upgrade to better postgres support if needed.

**Comment by pxp9** [comment]
We're planning to implement retries first, and then we will try to prioritize sqlite.

Thank you for your feedback.

**Comment by skirodev** [comment]
@pxp9 Hi! I would like to ask when it will be possible to support SQLite after two months. Is there any progress that can be known?

**Comment by pxp9** [comment]
We will try to implement it as soon as possible. I am currently studying and @ayrat555 is working on his job. We only are 2 maintainers in the project so it is hard to do this.

**Comment by pxp9** [comment]
> @pxp9 Hi! I would like to ask when it will be possible to support SQLite after two months. Is there any progress that can be known?

@skirodev do not worry because it will be done, probably will be done in Xmas holidays.

**Comment by IgnisDa** [comment]
@pxp9 Anything I can do to help?

**Comment by ayrat555** [comment]
@IgnisDa hey. it's almost done. but if you want to contribute, you can try to look into surrealdb - in-memory db
